# Generated by Django 5.0.4 on 2024-04-25 08:11

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cloth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article', models.CharField(max_length=40, unique=True, verbose_name='Артикль')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('description', models.TextField(verbose_name='Описание')),
                ('color', models.CharField(blank=True, max_length=50, verbose_name='Цвет')),
                ('width', models.CharField(max_length=20, verbose_name='Ширина')),
                ('composition', models.CharField(max_length=100, verbose_name='Состав')),
                ('density', models.CharField(max_length=20, verbose_name='Плотность')),
                ('length', models.CharField(blank=True, max_length=20, verbose_name='Длина')),
                ('country', models.CharField(blank=True, max_length=50, verbose_name='Страна производства')),
                ('image_url_1', models.URLField()),
                ('image_url_2', models.URLField(null=True)),
                ('image_url_3', models.URLField(null=True)),
                ('image_url_4', models.URLField(null=True)),
            ],
            options={
                'verbose_name': 'Ткань',
                'verbose_name_plural': 'Ткани',
            },
        ),
        migrations.CreateModel(
            name='ClothPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена')),
                ('date_updated', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата обновления')),
                ('cloth', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_history', to='clothes.cloth', verbose_name='Ткань')),
            ],
            options={
                'verbose_name': 'История цены',
                'verbose_name_plural': 'История цен',
                'ordering': ('-cloth',),
            },
        ),
    ]
